name: IdolBirthday
options:
  deploymentTarget:
    iOS: 13.5
    macOS: 11.0
  createIntermediateGroups: true
settings:
  DEVELOPMENT_TEAM: 4XKKKM86RN
settingGroups:
  # Catalyst-${platform} で参照する
  # これをやらないと macOS ターゲットなのに Catalyst の設定が出てくることがある気がする (要検証)
  Catalyst-iOS:
    SUPPORTS_MACCATALYST: true
  Catalyst-macOS: {}
packages:
  Backend:
    path: Backend
targets:
  # --- App ---
  App iOS:
    type: application
    platform: iOS
    deploymentTarget: 13.5
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: iOS/App/Resources/IdolBirthday.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: jp.pronama.IdolBirthday
        PRODUCT_NAME: IdolBirthday
      groups:
      - Catalyst-iOS
    sources:
    - path: iOS/App
    dependencies:
    - package: Backend
    - target: Widget iOS
  App macOS:
    type: application
    platform: macOS
    settings:
      CODE_SIGN_ENTITLEMENTS: App/macOS/IdolBirthday.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: jp.pronama.IdolBirthday
      PRODUCT_NAME: IdolBirthday
    sources:
    - path: App/Shared
    - path: App/macOS
    dependencies:
    - package: Backend
    - target: Widget macOS
  # --- Widget ---
  Widget:
    name: "Widget ${platform}"
    type: app-extension
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: 14.0
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Widget/${platform}/${platform}.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: jp.pronama.IdolBirthday.IdolBirthdayWidget
        PRODUCT_NAME: IdolBirthdayWidget
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
      groups:
      - Catalyst-${platform}
    sources:
    - path: Widget/Shared
    - path: Widget/${platform}
    dependencies:
    - package: Backend